version: '2'
services:
  cobranca-app:
    image: cobranca
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cobranca-postgresql:5432/cobranca
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  cobranca-postgresql:
    extends:
      file: postgresql.yml
      service: cobranca-postgresql
