-- Inicio tabela de telefones
CREATE TABLE TB_TELEFONES (
    ID_TELEFONE int NOT NULL,
    NU_TELEFONE varchar(11) NOT NULL,
    TP_LINHA varchar(20),
    CONSTRAINT PK_TELEFONE PRIMARY KEY (ID_TELEFONE)
);

CREATE SEQUENCE SQ_TELEFONE;
-- fim tabela de telefones

-- Inicio tabela de Email
CREATE TABLE TB_EMAILS (
    ID_EMAL int NOT NULL,
    DS_EMAIL varchar(255) NOT NULL,
    CONSTRAINT PK_EMAIL PRIMARY KEY (ID)
);

CREATE SEQUENCE SQ_EMAIL;
-- fim tabela de Email

-- Inicio tabela Endereco

CREATE TABLE TB_ENDERECO (
    ID_ENDERECO int NOT NULL,
    DS_LOGRADOURO varchar(255) NOT NULL,
    NU_ENDERECO int(6) NOT NULL,
    DS_COMPLEMENTO varchar(255) NOT NULL,
    NO_BAIRRO VARCHAR(255) NULL,
    NU_CEP VARCHAR(7) NOT NULL,
    NO_CIDADE VARCHAR(255) NOT NULL,
    NO_UF VARCHAR(255) NOT NULL,
    CONSTRAINT PK_EMAIL PRIMARY KEY ID_ENDERECO)
);

CREATE SEQUENCE SQ_ENDERECO;
-- Fim tabela Endereco

